-- Rodar isso uma vez no SQL Editor do Supabase (projeto lafowygavlydugtlwpwv)
-- para criar a tabela de posts do blog.

create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  content text not null,
  cover_image text,
  published boolean default true,
  created_at timestamptz default now()
);

alter table posts enable row level security;

-- Mesmo modelo de acesso já usado na tabela "cartas": leitura e escrita
-- liberadas pela chave anon, protegidas apenas pelo PIN do admin.html.
create policy "Public read posts" on posts for select using (true);
create policy "Public insert posts" on posts for insert with check (true);
create policy "Public update posts" on posts for update using (true);
create policy "Public delete posts" on posts for delete using (true);
